# Generated by Django 4.1.7 on 2024-03-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
